
<div class="field contact_phone required">
    <label class="label" for="contact_phone">
        <span><?= $block->escapeHtml(__('Contact number')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="contact_phone" id="contact_phone" value="" title="<?= $block->escapeHtmlAttr(__('Contact number')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field company_type required">
    <label class="label" for="company_type">
        <span><?= $block->escapeHtml(__('Company Type')) ?></span>
    </label>
    <div class="control">
        <select id="company_type" name="company_type" title="company type" class="validate-select" >
            <option value="" style="display:none;"><?= $block->escapeHtml(__('Please select a company type.')) ?></option>
            <option value="1"><?= $block->escapeHtml(__('CBD Manufacturer')) ?></option>
            <option value="2"><?= $block->escapeHtml(__('CBD Brand and Marketing company')) ?></option>
            <option value="3"><?= $block->escapeHtml(__('CBD Extractor')) ?></option>
            <option value="4"><?= $block->escapeHtml(__('Other')) ?></option>
        </select>
    </div>
</div>

<div class="field organization_name required" style="display:none;">
    <label class="label" for="organization_name">
        <span><?= $block->escapeHtml(__('Organization name')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="organization_name" id="organization_name" value="" title="<?= $block->escapeHtmlAttr(__('Organization name')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>


<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            $("#company_type").change(function(){
                var selectedValue = $(this).children("option:selected").val();
                if(selectedValue=='4')
                {
                    $(".organization_name").show();
                }
                else 
                {
                    $(".organization_name").hide();
                }
            });
        });
    });
</script>