<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Deliverydate
 */
?>
<section class="admin__page-section amasty-deliverydate">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Delivery Information'); ?></span>
        <?php if ($this->isOrderViewPage()): ?>
            <div class="actions"><a href="<?= $this->getEditUrl(); ?>"><?= __('Edit'); ?></a></div>
        <?php endif; ?>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item" style="width: 49%;">
            <?php $fields = $this->getDeliveryDateFields(); ?>
            <?php if (!empty($fields)): ?>
                <table class="admin__table-secondary">
                    <?php foreach ($fields as $field): ?>
                        <tr>
                            <td><?= $block->escapeHtml($field['label']); ?></td>
                            <td style="text-align: right;"><?= $block->escapeHtml($field['value']); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
        </div>
    </div>
</section>
